# Mod Naming Section.
modBaseName=mwr
modDisplayName=Wargames: Modern Warfare Reworked
# Further mod info needs to be entered into the mcmod.info file.

# Mod Versioning Section.
# Main Version and Sub Version are manual changes.
modMainVersion=1
modSubVersion=0
# The Build Number will auto-increment based on builds done, manual changes are still available.
modBuildNumber=0